---
title: "Untitled"
author: "Vanessa Trujillo"
date: "2/18/2019"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
Project1_Data <- read_csv("Documents/Class Documents/Stats/Stats 382/R Code/Project1-Data.csv")
```

#Part One
``` {r}
#namesrows <- c("Apples", "Oranges", "Cucumbers", "Grapes", "Bananas", "Mangos", "Strawberries", "Coconuts", "Dates", "Blueberries")

dat<-data.frame(Project1_Data, row.names = NULL, check.rows = FALSE, check.names = TRUE, fix.empty.names = FALSE, stringsAsFactors = default.stringsAsFactors())

default.stringsAsFactors()

namesrows <- c("Apples", "Oranges", "Cucumbers", "Grapes", "Bananas", "Mangos", "Strawberries", "Coconuts", "Dates", "Blueberries")
names(dat) <-namesrows
dat

dat$Computed_Column <- dat$Apples*dat$Cucumbers
dat
```


``` {r}
#summary(dat)
missingValues <- which(is.na(dat), arr.ind=TRUE)
missingValues

newdat <- na.omit(dat)
newdat



colA1 <- which(newdat$Col10 == "A1")
colA1
datA1 <- dat[colA1,c(1:10)]
datA1
colA2 <- which(newdat$Col10 == "A2")
colA2
datA2 <- dat[colA2,c(1:10)]
datA2
colA3 <- which(newdat$Col10 == "A3")
colA3
datA3 <- dat[colA3,c(1:10)]
datA3
colA4 <- which(newdat$Col10 == "A4")
colA4
datA4 <- dat[colA4,c(1:10)]
datA4


```